### ISSUE TITLE
Ansi Escape Codes in file output

### ISSUE THREAD

**Issue by tonoitp** [Kircheneer/netlint#16]
When using -o to write output to file, you get all ansi color codes in there. One would expect plain text.

**Comment by Kircheneer** [comment]
I will probably re-introduce the `-p/--plain` flag which I converted to `-q/--quiet` as I see they fulfill different purposes after all. Until then you can use `-q/--quiet` manually - that should fix the issue you are having.

**Comment by tonoitp** [comment]
in that case, consider csv export too ;)

**Comment by Kircheneer** [comment]
ANSI escape codes should be gone from output. I will consider CSV export for the near future, too.

**Comment by Kircheneer** [comment]
CSV output is now on the master with `--format csv` and probably `-o something.csv` as well - although it does work when writing to stdout.
