### ISSUE TITLE
NXOS FEX support

### ISSUE THREAD

**Issue by Kircheneer** [Kircheneer/netlint#26]
Support checks for the following scenarios:

- `feature fex` enabled but never used
- `switchport mode fex-fabric` without `fex associate`
- `fex associate` with unknown fex id

Test beforehand if commiting these errors to the configuration is actually possible.

**Comment by ChristopherJHart** [comment]
## FEX Feature-Set Installation on Nexus 9000
On Nexus 9000 series switches, `install feature-set fex` configuration is required before `feature-set fex` can be configured:
```
N9K# configure terminal
Enter configuration commands, one per line. End with CNTL/Z.
N9K(config)# feature-?
  feature-set  Enable feature-set

N9K(config)# feature-set ?
                               ^
% Invalid command at '^' marker.
N9K(config)# install feature-set ?
  fcoe      FCOE
  fcoe-npv  FCOE-NPV
  fex       FEX
  mpls      MPLS

N9K(config)# install feature-set fex
N9K(config)# show running-config | include install.feature
install feature-set fex
N9K(config)# feature-set ?
  fex  Installed feature-set

N9K(config)# feature-set fex
N9K(config)# show running-config | include feature-set
install feature-set fex
  allow feature-set fex
feature-set fex
```
I've tested and confirmed that `install feature-set fex` is not applicable for other Nexus platforms (e.g. Nexus 5000, 6000, 7000). This is only applicable to Nexus 9000 switches.

This means that on Nexus 9000 series switches, it is theoretically possible for `install feature-set fex` to be configured, but not `feature-set fex`. This is one scenario we can check for.

## FEX Feature On Nexus 5000/6000
Nexus 5000 and 6000 switches do not have `feature-set fex` configuration. They do have `feature fex` configuration. This means it's possible for `feature fex` to be configured without any other FEX configuration.
```
N5K-C5672UP# show running-config fex 

!Command: show running-config fex
!Time: Sat May  1 11:49:40 2021

version 7.3(7)N1(1b)
feature fex

N5K-C5672UP# configure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
N5K-C5672UP(config)# interface port-channel101
N5K-C5672UP(config-if)# switchport mode fex-fabric 
N5K-C5672UP(config-if)# fex associate 101
N5K-C5672UP(config-if)# show running-config fex 

!Command: show running-config fex
!Time: Sat May  1 11:50:18 2021

version 7.3(7)N1(1b)
feature fex

fex 101
  pinning max-links 1
  description "FEX0101"

interface port-channel101
  fex associate 101
```

## FEX Fabric Port-Channels Without Fex Association
`switchport mode fex-fabric` is required for `fex associate` configuration to be present:
```
N9K# configure terminal
Enter configuration commands, one per line. End with CNTL/Z.
N9K(config)# interface port-channel101
N9K(config-if)# fex associate 101
ERROR: Invalid port mode - port is not in fex-fabric mode
```
In other words, it's not possible for `fex associate {id}` to be present without `switchport mode fex-fabric` being also present.

It is possible for `switchport mode fex-fabric` to be configured without `fex associate` (which would be FEX misconfiguration, as the attached FEX would never come online).
```
N9K# configure terminal
Enter configuration commands, one per line. End with CNTL/Z.
N9K(config)# interface port-channel101
N9K(config-if)# switchport mode fex-fabric
N9K(config-if)# show running-config interface port-channel101

!Command: show running-config interface port-channel101
!Running configuration last done at: Sat May  1 15:37:00 2021
!Time: Sat May  1 15:37:04 2021

version 9.3(5) Bios:version 05.42 

interface port-channel101
  switchport mode fex-fabric
```

## FEX Global Configuration Without FEX Association
It is possible for `fex {id}` configuration to be present without `fex associate {id}` configuration present on a FEX fabric port-channel on Nexus 9000 series switches. `fex {id}` configuration is typically created when `fex associate {id}` is configured on a FEX fabric port-channel, but can also be manually configured.
```
N9K# show running-config fex 

!Command: show running-config fex
!Running configuration last done at: Sat May  1 15:37:00 2021
!Time: Sat May  1 15:37:19 2021

version 9.3(5) Bios:version 05.42 
install feature-set fex
feature-set fex


interface port-channel101
  switchport mode fex-fabric

N9K# configure terminal
Enter configuration commands, one per line. End with CNTL/Z.
N9K(config)# interface port-channel101
N9K(config-if)# fex associate 101
N9K(config-if)# show running-config fex

!Command: show running-config fex
!Running configuration last done at: Sat May  1 15:37:30 2021
!Time: Sat May  1 15:37:32 2021

version 9.3(5) Bios:version 05.42 
install feature-set fex
feature-set fex

fex 101
  pinning max-links 1
  description "FEX0101"

interface port-channel101
  switchport mode fex-fabric
  fex associate 101

N9K(config)# fex 102
N9K(config-fex)# description EXAMPLE
N9K(config-fex)# show running-config fex 

!Command: show running-config fex
!Running configuration last done at: Sat May  1 15:42:39 2021
!Time: Sat May  1 15:42:42 2021

version 9.3(5) Bios:version 05.42 
install feature-set fex
feature-set fex

fex 101
  pinning max-links 1
  description "FEX0101"
fex 102
  pinning max-links 1
  description "EXAMPLE"

interface port-channel101
  switchport mode fex-fabric
  fex associate 101
```

## Summary
I would say this issue can be sub-divided into the following checks:

1. Check that alerts if `install feature-set fex` is present, but `feature-set fex` is not present.
2. Check that alerts if `feature-set fex` or `feature fex` is present, but `fex {id}` or `fex associate {id}` is not present.
3. Check that alerts if `switchport mode fex-fabric` is present on an interface (either physical or port-channel, as some Nexus platforms allow FEX configuration on a physical interface while others require it to be under a port-channel), but `fex associate {id}` is not present on the same interface.
4. Check that alerts if `fex {id}` is globally configured, but `fex associate {id}` is not present on an interface (either physical or port-channel, as some Nexus platforms allow FEX configuration on a physical interface while others require it to be under a port-channel).

**Comment by Kircheneer** [comment]
Thank you!

Implemented in master now.
