### ISSUE TITLE
Positive CLI feedback when no checks fail

### ISSUE THREAD

**Issue by tonoitp** [Kircheneer/netlint#4]
Running against an 'faulty' config gives neat red failures
```
me@test:~/Code/dev/netlint$ netlint --nos cisco_ios tests/cisco_ios/configurations/my5505.conf
IOS101 Plaintext user passwords in configuration.
-> username localadm password 3uWn551eELjd/HkD encrypted
-> username admin password c0gyFG.7/sEHV/1G encrypted
---snip---
me@test:~/Code/dev/netlint$ 
```

where as an 'optimal' config shows nothing
```
me@test:~/Code/dev/netlint$ netlint --nos cisco_ios tests/cisco_ios/configurations/good.conf
me@test:~/Code/dev/netlint$
```

I'd like (an option?) to see output of passed test e.g. in green. That way you also see what has been checked.
And while we are at it.... 
Green for passed
Orange for warnings
Red for serious misses

**Comment by Kircheneer** [comment]
I think implementing this shouldn't hurt.

On a seperate note - what kind of NOS/device are you running that produces these configuration lines?

```username localadm password 3uWn551eELjd/HkD encrypted```

Currently these break the IOS101 check - should they show up.

**Comment by Kircheneer** [comment]
For anyone reading this, the configuration file is from a Cisco ASA.
