### ISSUE TITLE
Auto-detect NOS

### ISSUE THREAD

**Issue by Kircheneer** [Kircheneer/netlint#9]
Auto-detect the network operating system the configuration is for instead of having to pass it with `--nos`. Enables linting different NOSes with a single command.

**Comment by Kircheneer** [comment]
Fixed by #14

**Comment by itdependsnetworks** [comment]
I would be weary of this, I get that it makes sense to make it "easy" but the simple "feature check" now, will not scale, and then you have set the wrong expectation to your user. I do not think it is unreasonable for users to provide a proper inventory, or usage of several "conventions" such as decorate each file (e.g. #cisco_ios on first line) or using standard folder structure (e.g. /<platform>/<device>.cfg such as /cisco_ios/nyc-rt01.cfg)
